AWSTemplateFormatVersion: "2010-09-09"
Description: > 
   Template to create VPC in us-east-1 region
   Author: Ajmal
   Company: test
Resources:
  Name: MyFeb-VPC
  myVPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 100.100.0.0/16
      Tags:
       - Key: stack
         Value: production