AWSTemplateFormatVersion: "2010-09-09"
Description: > 
   Template to create VPC in us-east-1 region
   Author: Ajmal
   Company: test
Resources:
  myVPC: MyNewVPC
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
       - Key: stack
         Value: production