name: Create VPC demo
on:
    workflow_dispatch:
      inputs:
        environment:
          description: Target environment runs manually
          required: true
          type: string
jobs:
  create-vpc:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check credential details
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: ls -lR
#      - run: aws cloudformation create-stack --stack-name prod-vpc --template-body file://vpc.yaml
#      - run: aws ec2 describe-vpcs
