name: Create-VPC-Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment runs manually
        required: true
        type: string
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
#      - uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
      # - run: ls -lR
      # - run: aws cloudformation create-stack --stack-name MyFeb-vpc --template-body file://cloudformation/vpc.yaml
      # - run: sleep 20
      # - run: aws cloudformation describe-stack-events --stack-name MyFeb-vpc
       - run: ls -lR
       - run: aws cloudformation create-stack --stack-name prod-vpc --template-body file://cloudformation/vpc.yaml
       - run: sleep 20
       - run: aws cloudformation describe-stack-events --stack-name prod-vpc